site_name: PandasLazy
repo_url: https://github.com/mariotaddeucci/pandas-lazy
repo_name: mariotaddeucci/pandas-lazy
theme:
  name: material
  logo: images/SF.png
  favicon: images/SF.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: #091c79
      accent: #cce8fe
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: #cce8fe
      accent: #091c79
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.tabs.link
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - toc.follow
plugins:
  #- include-markdown
  - search
  - mkdocstrings:
      handlers:
          python:
              paths: [src]

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
