[build-system]
build-backend = "hatchling.build"
requires = ["hatch-vcs", "hatchling"]

[dependency-groups]
dev = [
    "codespell",
    "mkdocs",
    "mkdocs-gen-files",
    "mkdocs-material[imaging]",
    "mkdocs-plotly-plugin",
    "mkdocstrings-python",
    "pandas",
    "pyarrow",
    "pyiceberg[sql-sqlite]",
    "pyprojectsort",
    "pytest-cov>=4.1.0,<5",
    "pytest>=8.3.3,<9",
    "ruff",
    "ssort",
    "taskipy>=1.14.1",
]

[project]
dependencies = ["duckdb"]
description = "The power of duckdb with the ease of pandas"
dynamic = ["version"]
name = "lazy_pandas"
readme = "README.md"
requires-python = ">=3.10"

[tool.codespell]
skip = ".git,.tox,./venv,./docs/site,./tests/assets/*"

[tool.coverage.report]
exclude_lines = [
    "def __repr__",
    "if TYPE_CHECKING:",
    "if __name__ == .__main__.:",
    "pass",
    "pragma: no cover",
    "raise NotImplementedError",
]

[tool.coverage.run]
omit = ["*/conftest.py", "*/tests/*"]
source = ["lazy_pandas"]

[tool.hatch.build]
exclude = ["/tests"]

[tool.hatch.version]
path = "src/lazy_pandas/__init__.py"

[tool.pytest.ini_options]
addopts = "-vv"
pythonpath = "src"
testpaths = ["tests"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-unsafe-fixes = ["UP"]

[tool.taskipy.tasks]
build = "uv build"
docs-build = "cd docs && mkdocs build"
format = "ruff check --fix && ruff format && ssort && pyprojectsort"
lint = "ruff check && ruff format && ssort --check --check && codespell && pyprojectsort --check"
test = "pytest"
