name: Python package

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up UV
        run: python -m pip install uv

      - name: Generate documentation
        run: make docs-build

      - name: Execute lint checks
        run: make lint

      - name: Execute tests
        run: make test-all

      - name: Publish documentation
        run: make docs-deploy
