name: Python package

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Execute Hatch Test
        run: uvx hatch test

  StaticChecks:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Execute Ruff Check
        run: uvx ruff check

      - name: Execute Ruff Format Check
        run: uvx ruff format --check
