name: Python package

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up UV
        run: python -m pip install uv

      - name: Execute Hatch Test
        run: uvx hatch test

  StaticChecks:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Set up UV
        run: python -m pip install uv

      - name: Execute Ruff Check
        run: uvx ruff check

      - name: Execute Ruff Format Check
        run: uvx ruff format --check
